name: Build

on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        alpine_version: ["3.12", "3.13", "3.14"]
        pyinstaller_tag: ["3.6", "4.3"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          # For GITHUB_TOKEN to work, you have to give Write permission to the
          # repository for the Container Image in GitHub Packages.
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        run: |
          export SOURCE_COMMIT=${{ github.sha }}
          export SOURCE_REF=${{ github.ref }}

          ./build.sh \
            "${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}"
            "${{ matrix.pyinstaller_tag }}"
            "${{ matrix.alpine_version }}"
            "${{ matrix.python_version }}"

#      - name: Push container image
#        if: ${{ github.event_name != 'pull_request' && !env.ACT}}
#        run: |
